name: Geonode with QGIS Backend and GeoSAFE
description: Geonode with QGIS backend and GeoSAFE and backups via resilio sync
version: 2
category: GIS
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/docker-geosafe
