version: '2'
catalog:
  name: "InaSAFE Realtime v4"
  description: "InaSAFE Realtime using InaSAFE core v4"
  version: 2
  uuid: inasafe-realtime-v4-2
  questions:
    - variable: VOLUME_DRIVER
      label: Storage driver
      description: Storage driver used for volume
      type: "enum"
      options:
        - local
        - rancher-nfs
      default: local

    - variable: INAWARE_HOST
      label: InAWARE Host URL
      description: InAWARE URL for integration settings. Leave blank if not used.
      default: http://inaware.bnpb.go.id
      type: "string"
    - variable: INAWARE_USER
      label: InAWARE Username
      description: Credentials User for Realtime API to integrate with InAWARE
      default:
      type: "string"
    - variable: INAWARE_PASS
      label: InAWARE Password
      description: Credentials Password for Realtime API to integrate with InAWARE
      default:
      type: "password"
    - variable: INASAFE_REALTIME_REST_USER
      label: InaSAFE Realtime REST Username
      description: Credentials User for Realtime REST API
      default:
      type: "string"
    - variable: INASAFE_REALTIME_REST_PASSWORD
      label: InaSAFE Realtime REST Password
      description: Credentials Passwords for Realtime REST API
      default:
      type: "password"
    - variable: SHAKEMAP_DROP_EXPOSE_PORT
      label: SFTP Port for Shakemap drop
      description: This is SFTP exposed port into outside world
      default: 9222
      type: "string"
    - variable: SITE_DOMAIN_NAME
      label: InaSAFE Realtime Site Domain Name
      description: Internet resolvable domain name for InaSAFE Realtime. Used for redirect from InAWARE to InaSAFE. Must start with http:// and ends with /
      required: true
      default: http://realtime.inasafe.org/
      type: "string"

    - variable: POSTGRES_DB
      label: PostgreSQL db to create.
      required: true
      default: gis
      type: "string"
    - variable: POSTGRES_USER
      label: PostgrsSQL superuser account to create.
      required: true
      default: docker
      type: "string"
    - variable: POSTGRES_PASS
      label: PostgreSQL superuser password to create.
      required: true
      default: docker
      type: "string"
    - variable: REPLICATE_FROM
      description: Fill this if you need the initial db replicated from other sources
      label: Database replication master host
      default:
      type: "string"
    - variable: REPLICATE_PORT
      description: Fill this if you need the initial db replicated from other sources
      label: Database replication master port
      default:
      type: "string"

    - variable: POSTGRES_HBA_RANGE
      label: "Database allowed hosts"
      description: "PostgreSQL pg_hba (host based authentication) address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses."
      required: true
      default: 0.0.0.0/0
      type: "string"
    - variable: ADMIN_EMAIL
      label: "Administrator email"
      description: "Primary contact email for the site e.g. 'bob@foo.com'."
      required: true
      default: ""
      type: "string"
    - variable: SITE_URL
      label: "Site URL"
      description: "Primary URL for the site e.g. 'foo.com' (do not include http:// and doesn't end with /)."
      required: true
      default: ""
      type: "string"

    - variable: WEBSERVER_PORT
      label: "Website port"
      description: "Port on which the site should be served. Typically 80"
      required: true
      default: 80
      type: "int"

    - variable: SYNC_DEVICE_PREFIX
      label: "BtSync Device prefix"
      description: "Device prefix used by BtSync. Useful to differentiate sync devices."
      required: true
      default:
      type: "string"

    - variable: SSH_CONFIG_SYNC
      label: "SSH Config Key"
      description: "BtSync Key for SSH Config"
      type: "string"
    - variable: SSH_DATA_SYNC
      label: "SSH Data Key"
      description: "BtSync Key for SSH Data"
      type: "string"
    - variable: MEDIA_SYNC
      label: "Media Key"
      description: "BtSync Key for Media"
      type: "string"

    - variable: ANALYSIS_CONTEXT_SYNC
      label: "Analysis Data Key"
      description: "BtSync Key for Analysis Context"
      type: "string"
    - variable: REPORT_TEMPLATE_SYNC
      label: "Report Template Data Key"
      description: "BtSync Key for Report Template"
      type: "string"
services:
  sftppgbackup:
    scale: 1
    start_on_create: true
  smtp:
    scale: 1
    start_on_create: true
  sftpmediabackup:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
  indicator-worker:
    scale: 1
    start_on_create: true
  dbbackup:
    scale: 1
    start_on_create: true
  uwsgi:
    scale: 1
    start_on_create: true
  inasafe-worker:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true

  sftp:
    scale: 1
    start_on_create: true
  inasafe-shakemap-monitor:
    scale: 1
    start_on_create: true
  inasafe-worker:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  analysis-context-sync:
    scale: 1
    start_on_create: true
  report-template-sync:
    scale: 1
    start_on_create: true
