name: InaSAFE Realtime
description: InaSAFE Realtime server
version: 4.0.2
category: GIS
maintainer: Kartoza (Pty) Ltd. - Rizky Maulana Nugraha, rizky@kartoza.com
license: GPL v3
projectURL: https://github.com/inasafe/inasafe-django
