.catalog:
  name: "Docker OSM "
  description: "This is [PostGIS](http://postgis.org) 2.4 running on PostgreSQL 9.6 all set up and ready to go in Rancher."
  version: 1
  uuid: kartoza-postgis
  questions:
  - variable: POSTGRES_DB
    label: "PostgreSQL db to create."
    required: true
    default: gis
    type: "string"
  - variable: POSTGRES_USER
    label: "PostgrsSQL superuser account to create."
    required: true
    default: docker
    type: "string"
  - variable: POSTGRES_PASS
    label: "PostgreSQL superuser password to create."
    required: true
    default: docker
    type: "string"
  - variable: POSTGRES_HBA_RANGE
    label: "Database allowed hosts"
    description: "PostgreSQL pg_hba (host based authentication) address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses. NOTE That the default is to be open / public!"
    required: true
    default: 0.0.0.0/0
    type: "string"
  - variable: ALLOW_LISTEN_RANGE
    label: "Database IP range to listen to"
    description: "PostgreSQL conf (host based authentication) listen address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses. NOTE That the default is to be open / public!"
    required: true
    default: '*'
    type: "string"
  - variable: POSTGRES_PORT
    description: "Postgres port"
    label: "Port on which the database should be served. Typically 5432"
    required: true
    default: 5432
    type: "int"
  - variable: BTSYNC_DB_SECRET
    label: "Database backups key"
    description: "Resilio sync read/write key for syncing settings. Structure of Sync Directory
                  should resemble https://github.com/kartoza/docker-osm/tree/develop/settings"
    required: true
    default: ""
    type: "string"
  - variable: UPDATE_TIME
    description: "Time Interval for update cycle"
    label: "Seconds between 2 executions of the script. If 0, then no update will be done, only the first initial import from the PBF"
    required: true
    default: 120
    type: "int"
  - variable: TABLE_SRID
    description: "SRID"
    label: "SRID of Tables"
    required: true
    default: 4326
    type: "int"
  - variable: DB_SCHEMA
    label: "DB SCHEMA PRODUCTION"
    description: "See http://imposm.org/docs/imposm3/latest/tutorial.html#deploy-production-tables"
    required: true
    default: public
    type: "string"
  - variable: DB_SCHEMA_IMPORT
    label: "DB SCHEMA IMPORT"
    description: "See http://imposm.org/docs/imposm3/latest/tutorial.html#deploy-production-tables"
    required: true
    default: import
    type: "string"
  - variable: DB_SCHEMA_BACKUP
    label: "DB SCHEMA BACKUP"
    description: "See http://imposm.org/docs/imposm3/latest/tutorial.html#deploy-production-tables"
    required: true
    default: backup
    type: "string"
  - variable: QGIS_STYLE_BOOLEAN
    label: "QGIS STYLE"
    description: "Install some styles if you are using the default mapping. It can be 'yes' or 'no'"
    required: true
    default: yes
    type: "string"
  - variable: CLIP_BOOLEAN
    label: "CLIP"
    description: "Use clip in the database. It can be 'yes' or 'no'"
    required: true
    default: no
    type: "string"
  - variable: MAX_RANGE
    description: "MAX DAYS"
    label: "The maximum time range to assemble a cumulated changefile."
    required: true
    default: 100
    type: "int"
  - variable: DIFF_VAL
    label: "DIFF"
    description: "Osmupdate uses a combination of minutely, hourly and daily changefiles. This value can be minute, hour, day or sporadic."
    required: true
    default: sporadic
    type: "string"
  - variable: MAX_MERGE_TIME
    description: "MAX MERGE"
    label: "The argument to determine the maximum number of parallely processed changefiles."
    required: true
    default: 7
    type: "int"
  - variable: COMPRESS_LEVEL
    description: "COMPRESSION LEVEL"
    label: "Define level for gzip compression. values between 1 (low compression but fast) and 9 (high compression but slow)"
    required: true
    default: 1
    type: "int"
  - variable: URL
    label: "BASE_URL"
    description: "Change the URL to use a custom URL to fetch regional file updates."
    required: true
    default: http://planet.openstreetmap.org/replication/
    type: "string"

  - variable: "HOST_AFFINITY"
    label: "Label of host to deploy on"
    description: |
      To keep containers running on specific
      hosts, provide label attached to host
      to deploy on. For example, if you create a label 
      when deploying your host with key gis-box-id
      and value 3 then you would enter here gis-box-id=3
    required: true
    type: string
    default:
  services:
    db:
      scale: 1
      labels:
        io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}

