version: '2'
volumes:
  postgis-data:
  postgis-history-data:
  django-statics-data:
  django-media-data:
  nginx-conf-data:
services:

  rabbitmq:
    image: library/rabbitmq
    hostname: rabbitmq
    environment:
      - RABBIT_PASSWORD=rabbit_test_password
      - USER=rabbit_user
      - RABBITMQ_NODENAME=rabbit

  smtp:
    image: catatnight/postfix
    environment:
      # You could change this to something more suitable
    - maildomain=kartoza.com
    - smtp_user=noreply:docker
    restart: unless-stopped

  db:
    image: kartoza/postgis
    volumes:
      - postgis-data:/var/lib/postgresql
      - postgis-history-data:/backups
    environment:
      - ALLOW_IP_RANGE=${POSTGRES_HBA_RANGE}
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DBNAME=${POSTGRES_DB}
      # Postgres env var. For postgres CLI shortcut
      - PGUSER=docker
      - PGPASSWORD=${POSTGRES_PASS}
      - PGDBNAME=${POSTGRES_DB}
      - PGHOST=localhost
    restart: unless-stopped

  uwsgi:
    image: christiaanvdm/kartoza_django
    working_dir: /home/web/django_project
    environment:
      - PYTHONPATH=/home/web/django_project
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=${POSTGRES_PASS}
      - DATABASE_HOST=db
      - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
      - SITEURL=${SITE_URL}
      - DEBUG=${DJANGO_DEBUG_MODE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - MAILDOMAIN=${MAIL_DOMAIN}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_SUBJECT_PREFIX=${EMAIL_SUBJECT_PREFIX}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL}
    volumes:
      - django-statics-data:/home/web/static:rw
      - django-media-data:/home/web/media:rw
    links:
      - smtp:smtp
      - db:db
    restart: unless-stopped
    labels:
      io.rancher.container.pull_image: always


  sftp:

    image: atmoz/sftp
    volumes:
      - postgis-data:/home/ftp/postgis-data:rw
      - postgis-history-data:/home/ftp/postgis-history:rw
      - django-statics-data:/home/ftp/django-statics-data:rw
      - django-media-data:/home/ftp/django-media-data:rw
      - nginx-conf-data:/home/ftp/nginx/conf-data:rw
    ports:
      - "2222:22"
    command: kartoza:welovekartoza:1001

  dbbackups:
    image: kartoza/pg-backup:9.6
    entrypoint: []
    command: ["/start.sh"]
    volumes:
      - postgis-history-data:/backups
    links:
      - db:db
    environment:
      # take care to let the project name below match that
      # declared in the top of the makefile
      - DUMPPREFIX=PG_ford3
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGPORT=5432
      - PGHOST=db
      - PGDATABASE=gis
    restart: unless-stopped

  nginx-conf:
    image: kartoza/ford3_nginx_conf:v1.0.3-20190728
    volumes:
      - nginx-conf-data:/etc/nginx/sites-available
    environment:
      TARGET: /etc/nginx/sites-available
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'

  web:
    image: nginx
    entrypoint: /etc/nginx/sites-available/docker-entrypoint.sh

    {{- if eq .Values.DJANGO_DEBUG_MODE "True" }}

    command: dev

    {{- else }}

    command: prod

    {{- end }}
    volumes:
      - nginx-conf-data:/etc/nginx/sites-available
      - django-statics-data:/home/web/static:ro
      - django-media-data:/home/web/media:ro
    links:
      - uwsgi:uwsgi
    restart: unless-stopped