version: '2'
catalog:
  name: "InaSAFE Realtime v3.5"
  description: "InaSAFE Realtime using InaSAFE core v3.5."
  version: v3.5
  uuid: inasafe-realtime-v3.5-1
  minimum_rancher_version: v1.6.10
  questions:
    - variable: VOLUME_DRIVER
      label: Storage driver
      description: Storage driver used for volume
      type: "enum"
      options:
        - local
        - rancher-nfs
      default: local

    - variable: INAWARE_HOST
      label: InAWARE Host URL
      description: InAWARE URL for integration settings. Leave blank if not used.
      default: http://inaware.bnpb.go.id
      type: "string"
    - variable: INAWARE_USER
      label: InAWARE Username
      description: Credentials User for Realtime API to integrate with InAWARE
      default:
      type: "string"
    - variable: INAWARE_PASS
      label: InAWARE Password
      description: Credentials Password for Realtime API to integrate with InAWARE
      default:
      type: "password"
    - variable: INASAFE_REALTIME_REST_USER
      label: InaSAFE Realtime REST Username
      description: Credentials User for Realtime REST API
      default: realtimepush@realtime.inasafe.org
      type: "string"
    - variable: INASAFE_REALTIME_REST_PASSWORD
      label: InaSAFE Realtime REST Password
      description: Credentials Passwords for Realtime REST API
      default:
      type: "password"
    - variable: SHAKEMAP_DROP_EXPOSE_PORT
      label: SFTP Port for Shakemap drop
      description: This is SFTP exposed port into outside world
      default: 9222
      type: "string"
    - variable: SITE_DOMAIN_NAME
      label: InaSAFE Realtime Site Domain Name
      description: Internet resolvable domain name for InaSAFE Realtime. Used for redirect from InAWARE to InaSAFE. Must start with http:// and ends with /
      required: true
      default: http://realtime.inasafe.org/
      type: "string"

    - variable: POSTGRES_DB
      label: PostgreSQL db to create.
      required: true
      default: gis
      type: "string"
    - variable: POSTGRES_USER
      label: PostgrsSQL superuser account to create.
      required: true
      default: docker
      type: "string"
    - variable: POSTGRES_PASS
      label: PostgreSQL superuser password to create.
      required: true
      default: docker
      type: "string"
    - variable: REPLICATE_FROM
      description: Fill this if you need the initial db replicated from other sources
      label: Database replication master host
      default:
      type: "string"
    - variable: REPLICATE_PORT
      description: Fill this if you need the initial db replicated from other sources
      label: Database replication master port
      default:
      type: "string"

    - variable: POSTGRES_HBA_RANGE
      label: "Database allowed hosts"
      description: "PostgreSQL pg_hba (host based authentication) address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses."
      required: true
      default: 0.0.0.0/0
      type: "string"
    - variable: ADMIN_EMAIL
      label: "Administrator email"
      description: "Primary contact email for the site e.g. 'bob@foo.com'."
      required: true
      default: ""
      type: "string"
    - variable: SITE_URL
      label: "Site URL"
      description: "Primary URL for the site e.g. 'foo.com' (do not include http:// and doesn't end with /)."
      required: true
      default: ""
      type: "string"

    - variable: WEBSERVER_PORT
      description: "Website port"
      label: "Port on which the site should be served. Typically 80"
      required: true
      default: 80
      type: "int"

    - variable: SYNC_DEVICE_PREFIX
      label: "BtSync Device prefix"
      description: "Device prefix used by BtSync. Useful to differentiate sync devices."
      required: true
      default:
      type: "string"

    - variable: SSH_CONFIG_SYNC
      description: "BtSync Key for SSH Config"
      label: "SSH Config Key"
      type: "string"
    - variable: SSH_DATA_SYNC
      description: "BtSync Key for SSH Data"
      label: "SSH Data Key"
      type: "string"
    - variable: MEDIA_ALLOW_SYNC
      description: "Allow Media folder to sync"
      label: "Media Allow Sync"
      type: "boolean"
      default: true
    - variable: MEDIA_SYNC
      description: "BtSync Key for Media"
      label: "Media Key"
      type: "string"

    - variable: BMKG_ALLOW_SYNC
      description: "Allow BMKG Shakemaps to sync"
      label: "BMKG Shakemaps Allow Sync"
      type: "boolean"
      default: true
    - variable: BMKG_SYNC
      description: "BtSync Key for BMKG Shakemaps"
      label: "BMKG Shakemaps Key"
      type: "string"
    - variable: SHAKEMAPS_CORRECTED_ALLOW_SYNC
      description: "Allow BMKG Shakemaps Corrected to sync"
      label: "BMKG Shakemaps Corrected Allow Sync"
      type: "boolean"
      default: true
    - variable: SHAKEMAPS_CORRECTED_SYNC
      description: "BtSync Key for Shakemaps Corrected"
      label: "Shakemaps Corrected Key"
      type: "string"
    - variable: ANALYSIS_DATA_SYNC
      description: "BtSync Key for Analysis Data"
      label: "Analysis Data Key"
      type: "string"
    - variable: REPORT_TEMPLATE_SYNC
      description: "BtSync Key for Report Template"
      label: "Report Template Data Key"
      type: "string"
